# Generated by Django 4.2.5 on 2023-09-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losikshoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pembayaran',
            fields=[
                ('id_pembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('tanggal_pembayaran', models.DateField()),
                ('metode_pembayaran', models.CharField(max_length=30)),
            ],
        ),
    ]
