# Generated by Django 4.2.5 on 2023-09-16 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('losikshoes', '0002_pembayaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaksi',
            fields=[
                ('nomor_nota', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_transaksi', models.DateField()),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='losikshoes.pelanggan')),
                ('id_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='losikshoes.pembayaran')),
            ],
        ),
    ]
