# Generated by Django 4.2.5 on 2023-09-17 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('losikshoes', '0003_transaksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='perawatan',
            fields=[
                ('id_perawatan', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_perawatan', models.CharField(max_length=30)),
                ('durasi_pengerjaan', models.PositiveIntegerField()),
                ('harga_perawatan', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='detail_transaksi',
            fields=[
                ('id_detail_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('deskripsi_sepatu', models.CharField(max_length=100)),
                ('id_perawatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='losikshoes.perawatan')),
                ('nomor_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='losikshoes.transaksi')),
            ],
        ),
    ]
