# Generated by Django 4.2.5 on 2023-09-18 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('losikshoes', '0006_pembayaran_nomor_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='nomor_nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='losikshoes.transaksi'),
        ),
    ]
