# Generated by Django 4.2.5 on 2023-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losikshoes', '0007_alter_pembayaran_nomor_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='status',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
