# Generated by Django 4.2.5 on 2023-10-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losikshoes', '0008_remove_pembayaran_status_transaksi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='metode_pembayaran',
            field=models.BooleanField(default=False),
        ),
    ]
