# Generated by Django 4.2.5 on 2023-10-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('losikshoes', '0009_alter_pembayaran_metode_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_transaksi',
            name='id_perawatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='losikshoes.perawatan'),
        ),
    ]
